CREATE TABLE IF NOT EXISTS success_stories (
id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
title_ar TEXT NOT NULL,
title_en TEXT NOT NULL,
content_ar TEXT NOT NULL,
content_en TEXT NOT NULL,
author_name_ar TEXT NOT NULL,
author_name_en TEXT NOT NULL,
success_details_ar JSONB NOT NULL,
success_details_en JSONB NOT NULL,
key_takeaways_ar JSONB NOT NULL,
key_takeaways_en JSONB NOT NULL,
impact_ar TEXT NOT NULL,
impact_en TEXT NOT NULL,
start_date DATE NOT NULL,
end_date DATE NOT NULL,
categories JSONB NOT NULL,
location JSONB NOT NULL,
main_image JSONB NOT NULL,
images JSONB NOT NULL,
main_video JSONB,
videos JSONB,
main_file JSONB,
files JSONB,
audience_engagement JSONB NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);